swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - people
      summary: Read the entire list of people
      description: Read the list of people
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of people to get from People
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list to start gathering people
          required: false
      responses:
        200:
          description: Successful read people list operation
          schema:
            type: array
            items:
              properties:
                person_id:
                  type: string
                  description: Id of the person
                fname:
                  type: string
                  description: First name of the person
                lname:
                  type: string
                  description: Last name of the person
                timestamp:
                  type: string
                  description: Create/update timestamp of the person

    post:
      operationId: people.create
      tags:
        - people
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of person to create
              lname:
                type: string
                description: Last name of person to create
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              person_id:
                type: string
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Create/update timestamp of the person

  /people/{person_id}:
    get:
      operationId: people.read_one
      tags:
        - people
      summary: Read one person from the people list
      description: Read one person from the people list
      parameters:
        - name: person_id
          in: path
          description: Id of the person to get from the list
          type: integer
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            type: object
            properties:
              person_id:
                type: string
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Create/update timestamp of the person

    put:
      operationId: people.update
      tags:
        - people
      summary: Update a person in the people list
      description: Update a person in the people list
      parameters:
        - name: person_id
          in: path
          description: Id of the person to update
          type: integer
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of the person to update
              lname:
                type: string
                description: Last name of the person to update
      responses:
        200:
          description: Successfully updated person
          schema:
            properties:
              person_id:
                type: string
                description: Id of the person in the database
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Create/Update timestamp of the person record

    delete:
      operationId: people.delete
      tags:
        - people
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: person_id
          in: path
          type: integer
          description: Id of the person to delete
          required: True
      responses:
        200:
          description: Successfully deleted a person
